version: '3.1'
volumes:
  mongo_data:
services:
  api:
    restart: unless-stopped
    build: ./api
    ports:
      - 3001:3001
    volumes:
      - ./api:/usr/src/app
    command: npm start
    tty: true
    stdin_open: true
    depends_on:
      - mongo

  client:
    restart: unless-stopped
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
    command: npm start
    tty: true
    stdin_open: true
    depends_on:
      - api

  mongo:
    restart: unless-stopped
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017